### ISSUE TITLE
jupyterlab 3.0

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab-latex#154]
I have a version of jupyterlab-latex in my fork that works with 3.0

**Comment by enriqueartal** [comment]
I installed it and it works. It complains about the extension not being installed (maybe I skipped some step) but the pdf is produced.

**Comment by GoingMyWay** [comment]
Hello,

When will you support the jupyterlab 3?  jupyterlab-latex cannot install.

Best

**Comment by joequant** [comment]
FYI.  I have patches in my fork that installs jupyterlab-latex.

**Comment by fairread** [comment]
Hi @joequant thanks for the fork, but sorry noob question how to install it anyway? I tried the following terminal command

`$ npm install -g git+https://github.com/joequant/jupyterlab-latex.git`

but in the end received the following error:
`npm ERR! code ENOENT
npm ERR! path /usr/local/lib/node_modules/@jupyterlab/latex/node_modules/@webassemblyjs/helper-fsm
npm ERR! enoent ENOENT: Cannot cd into '/usr/local/lib/node_modules/@jupyterlab/latex/node_modules/@webassemblyjs/helper-fsm'
npm ERR! enoent This is related to npm not being able to find a file.`

**Comment by BrandenEsses** [comment]
Hi @fairread. You can clone @joequant's fork to your system with `git clone`,`cd` into the directory, then follow the install from source section of the [advanced usage instructions](https://github.com/jupyterlab/jupyterlab-latex/blob/master/docs/advanced.md) to install.

**Comment by blink1073** [comment]
@joequant a PR would be most welcome!

**Comment by Nairod26** [comment]
Hi all, for noob like me, i give you the comands to install it:
open a terminal then execute : `git clone https://github.com/joequant/jupyterlab-latex.git` 
Let it clone on your machine. Move in it : `cd jupyterlab-latex`
Once in, `pip3 install -e .`
Therefore we are going to install yarn `jlpm install`
Then we run it `jlpm run build`
To finish, the package installation `jupyter labextension install .`

**Comment by Micky71** [comment]
Hi folks, i've not success installation on windows 10, Jupyterlab 3.0.14
I'm still a noob on Python & Jupyterlab too.
First, I've to install git: 
https://gitforwindows.org/
There are many questions while the installation, but taken the proposed answers still works  I guess
( Have made two differences: ssh not OpenSSH rather than Windows Program and a second that I don't remember now. It was also an open source vs windows decision )
Then I run
 git clone https://github.com/joequant/jupyterlab-latex.git 
as described  and went to the new directory where git saved the extension files.
 'pip3 install -e .'  works for me too.
I didn't need to install jlpm, it was already installed.
BUT: 'jlpm run build' dont work:
(base) PS C:\Users\Micky\Jupyterlab_Latex\jupyterlab-latex> jlpm run build
yarn run v1.21.1
$ tsc
The "tsc" command is either misspelled or could not be found (Translation from DE → EN, the error message, probably other spelled on windows-EN)
What I've done on this point, was build the new Jupyterlabkernel:
'jupyter lab build'
And then i've run 
'jlpm run build':
 jlpm run build                                              yarn run v1.21.1
$ tsc
Done in 2.50s.
And finaly:
'jupyter labextension install .'
In the Jupyterlab the extension is mark to installed, but it doesn't work for me:
Server Extension Error
You probably do not have jupyterlab_latex installed or enabled. Please, run "pip install -U jupyterlab_latex." If that does not work, try "jupyter serverextension enable --sys-prefix jupyterlab_latex".
But i changes nothing.
Any suggestions?

**Comment by sntgluca** [comment]
Hi @joequant ,
did your fork become a PR for the main branch?
It would be so nice if jupyterlab3 would be officially supported...

**Comment by bollwyvl** [comment]
We've merged #171 and released `jupyterlab-latex` for both pip and conda:
- https://pypi.org/project/jupyterlab-latex/3.1.0/
- https://anaconda.org/conda-forge/jupyterlab_latex/files?version=3.1.0

One thing we _don't_ yet have is a downstream-developer-oriented release on npmjs, but this is probably a separate issue:
- https://www.npmjs.com/package/@jupyterlab/latex
